enable_selector = false
selector = "rofi -dmenu -i -p 'Open With: '"
term_exec_args = '-e'
expand_wildcards = false

[[handlers]]
exec = "freetube %u" # Uses desktop entry field codes
terminal = false # Set to true for terminal apps, false for GUI apps (optional; defaults to false)
regexes = ['(https://)?(www\.)?youtu(be\.com|\.be)/*.'] # Use single-quote literal strings

# Default browser - catches everything else
[[handlers]]
# exec = "/home/sar/.local/bin/mullvad-browser/Browser/mullvadbrowser.real"  # Replace with your browser's desktop entry
exec = "firefox"  # Replace with your browser's desktop entry
terminal = false
regexes = ['https://.*', 'http://.*']  # Catch-all patterns for http/https
