#!/bin/bash

# Check if hypridle is running
if pgrep -x "hypridle" > /dev/null; then
    # If running, kill it
    killall hypridle
    notify-send "Hypridle" "Disabled"
else
    # If not running, start it
    hypridle &
    notify-send "Hypridle" "Enabled"
fi
