[mgr]
show_hidden = true

[opener]
open = [
  # Redefine the default open opener so that it orphans by default
  # Copied all the contents inside open to redefine all the run conditions
  { run = 'xdg-open "$1"', orphan = true, desc = "Open", for = "linux" },
  { run = 'open "$@"', orphan = true, desc = "Open", for = "macos" },
  { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
  { run = 'termux-open "$1"', desc = "Open", for = "android" },
]
