[mgr]
show_hidden = true

[opener]
open = [
  # Redefine the default open opener so that it orphans by default
  # Copied all the contents inside open to redefine all the run conditions
  { run = 'xdg-open "$1"', orphan = true, desc = "Open", for = "linux" },
  { run = 'open "$@"', orphan = true, desc = "Open", for = "macos" },
  { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
  { run = 'termux-open "$1"', desc = "Open", for = "android" },
]

play = [
  # The play opener does't work by default
  # Copying the content from default play opener as is seems to work
  { run = 'xdg-open "$1"', desc = "Play", for = "linux" },
  { run = 'open "$@"', desc = "Play", for = "macos" },
  { run = 'start "" "%1"', orphan = true, desc = "Play", for = "windows" },
  { run = 'termux-open "$1"', desc = "Play", for = "android" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
  { run = 'mediainfo "%1" & pause', block = true, desc = "Show media info", for = "windows" },
]
