# # Default workspaces
# windowrule = workspace 1, class:^(zen)$
# windowrule = workspace 1, class:^(helium)$
# windowrule = workspace 2, class:^(com.mitchellh.ghostty)$
# windowrule = workspace 2, class:^(org.omarchy.nvim)$
# windowrule = workspace 2, class:^(chrome-github.com__-Default)$
# windowrule = workspace 3, class:^(org.pwmt.zathura)$
# windowrule = workspace 4, class:^(com.sar.newsraft)$
# windowrule = workspace 4, class:^(mpv)$
# windowrule = workspace 5, class:^(signal)$
# windowrule = workspace 5, class:^(chrome-web.whatsapp.com__-Default)$
# windowrule = workspace 6, class: ^(virt-manager)$
# # Screen sharing
# windowrule = float, class:^(hyprland-share-picker)$
# windowrule = size 631 290, class:^(hyprland-share-picker)$
# # Floating windows
# windowrule = float, size 875 600, class:^(chrome-chatgpt.com__-Default)$
# windowrule = float, size 875 600, class:^(org.omarchy.yazi)$
# windowrule = float, size 875 600, class:^(org.omarchy.rmpc)$
# # windowrule = float, size 875 600, title:^(Unlock Database - KeePassXC)$
# # windowrule = float, size 875 600, title:^(KeePassXC - Passkey credentials)$
# windowrule = float, size 875 600, class:^(org.keepassxc.KeePassXC)$
# windowrule = float, size 875 600, class:^(GTK Application)$

# Default workspaces
windowrule = workspace 1, match:class ^(zen)$
windowrule = workspace 1, match:class ^(helium)$
windowrule = workspace 2, match:class ^(com.mitchellh.ghostty)$
windowrule = workspace 2, match:class ^(org.omarchy.nvim)$
windowrule = workspace 2, match:class ^(chrome-github.com__-Default)$
windowrule = workspace 3, match:class ^(org.pwmt.zathura)$
windowrule = workspace 4, match:class ^(com.sar.newsraft)$
windowrule = workspace 4, match:class ^(mpv)$
windowrule = workspace 5, match:class ^(signal)$
windowrule = workspace 5, match:class ^(chrome-web.whatsapp.com__-Default)$
windowrule = workspace 6, match:class ^(virt-manager)$
# Screen sharing
windowrule = float on, size 631 290, match:class ^(hyprland-share-picker)$
# Floating windows
windowrule = float on, size 875 600, match:class ^(chrome-chatgpt.com__-Default)$
windowrule = float on, size 875 600, match:class ^(org.omarchy.yazi)$
windowrule = float on, size 875 600, match:class ^(org.omarchy.rmpc)$
# windowrule = float, size 875 600, title:^(Unlock Database - KeePassXC)$
# windowrule = float, size 875 600, title:^(KeePassXC - Passkey credentials)$
windowrule = float on, size 875 600, match:class ^(org.keepassxc.KeePassXC)$
windowrule = float on, size 875 600, match:class ^(GTK Application)$
