#############################
### ENVIRONMENT VARIABLES ###
#############################
# See https://wiki.hyprland.org/Configuring/Environment-variables/
#Default Editor
env = EDITOR,nvim
#Cursor theme
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,rose-pine-hyprcursor
env = HYPRSHOT_DIR,/home/sar/Pictures/Screenshots/
#Qt theme
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
#env = QT_STYLE_OVERRIDE,kvantum 
#GCM (Git Credential Manager)
env = GCM_CREDENTIAL_STORE,secretservice
env = PATH,$PATH:/home/sar/.local/bin
