#!/usr/bin/sh

export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATAFORM=wayland

dbus-update-activation-environment --systemd --all

exec systemd-cat --identifier=dwl dwl "$@"
